Ignore unnecessary_box_returns pedantic clippy lint
    error: boxed return of the sized type `expr::Expr`
       --> src/pat.rs:671:31
        |
    671 |         fn into_expr(self) -> Box<Expr> {
        |                               ^^^^^^^^^ help: try: `expr::Expr`
        |
        = help: changing this also requires a change to the return expressions in this function
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_box_returns
        = note: `-D clippy::unnecessary-box-returns` implied by `-D clippy::pedantic`