Fix rustdoc example code for 2021 edition
    ---- src/expr.rs - expr::Arm (line 930) stdout ----
    error[E0783]: `...` range patterns are deprecated
     --> src/expr.rs:934:5
      |
    6 |     0...10 => {
      |     ^---^^
      |      |
      |      help: use `..=` for an inclusive range

    ---- src/lib.rs - parse_file (line 927) stdout ----
    error[E0782]: trait objects must include the `dyn` keyword
     --> src/lib.rs:932:28
      |
    8 | fn run() -> Result<(), Box<Error>> {
      |                            ^^^^^
      |
    help: add `dyn` keyword before this trait
      |
    8 | fn run() -> Result<(), Box<dyn Error>> {
      |                            +++