Move syn-codegen crate to own workspace
Fixes this error when attempting to build syn with a compiler older
than 1.64:

    error: failed to select a version for the requirement `hashbrown = "^0.14"`
    candidate versions found which didn't match: 0.13.2, 0.13.1, 0.12.3, ...
    location searched: crates.io index
    required by package `indexmap v2.0.0`
        ... which satisfies dependency `indexmap = "^2"` of package `syn-codegen v0.4.0`