Add regression test for chained comparisons with bailout
    thread 'test_fixup' panicked at tests/test_expr.rs:843:25:
    failed to parse `x > .. > x`: comparison operators cannot be chained
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace