Somewhat better scope span for Macro::parse_body
This at least works when proc-macro2 is in fallback mode.

    error[cxxbridge]: expected `>`
      ┌─ tests/ui/include.rs:6:26
      │
    6 │         include!(<path/to);
      │                          ^ expected `>`

There's no effect when proc-macro2 is in wrapper mode. For that to work
we would need to preserve the real original Group token rather than just
its Span. Only the proc_macro::Group can return a meaningful close span.

    error: expected `>`
     --> $DIR/include.rs:6:17
      |
    6 |         include!(<path/to);
      |                 ^^^^^^^^^^