Temporarily disable nightly testing due to libLLVM link issue
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" cc -m64 /tmp/rustcPYQ6e2/symbols.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.00.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.01.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.02.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.03.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.04.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.05.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.06.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.07.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.08.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.09.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.10.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.11.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.12.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.13.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.14.rcgu.o target/release/deps/test_precedence-6bd9c16ceacbfa39.test_precedence.516dd8336f7f7b26-cgu.15.rcgu.o -Wl,--as-needed -L target/release/deps -L ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib -Wl,-Bstatic target/release/deps/libreqwest-8f37388bf1e63fc8.rlib target/release/deps/librustls_pemfile-14952b380480d6bc.rlib target/release/deps/libhyper_tls-745fbbf90ab75538.rlib target/release/deps/libbase64-bed3832b4ea762bf.rlib target/release/deps/libipnet-86ea84f9be226c24.rlib target/release/deps/libtokio_native_tls-b768b6ee0a336e6d.rlib target/release/deps/libserde_urlencoded-3126bb0d70af8156.rlib target/release/deps/libryu-d6e6a36d6310bcaf.rlib target/release/deps/libmime-1d8c19b154c86676.rlib target/release/deps/libencoding_rs-f4d0330390db5820.rlib target/release/deps/libserde-770080fa0a5f3c5e.rlib target/release/deps/libnative_tls-52417f9597229180.rlib target/release/deps/libopenssl_probe-f8f2b8f74e81afe3.rlib target/release/deps/libopenssl-4434968f269261a4.rlib target/release/deps/libforeign_types-f0310e3b6d158a3d.rlib target/release/deps/libforeign_types_shared-6699a04f3d5ec3c6.rlib target/release/deps/libopenssl_sys-b3a6e8fa895015c4.rlib target/release/deps/libhyper-e21aafa58595f0fe.rlib target/release/deps/libwant-cf0de057298d16fa.rlib target/release/deps/libtry_lock-cf58c52febbc5084.rlib target/release/deps/libhttparse-f3b0a4fe841a550c.rlib target/release/deps/libh2-a6a1eeb6f47af968.rlib target/release/deps/libindexmap-33b660851ca98df4.rlib target/release/deps/libequivalent-ec054357584dda9d.rlib target/release/deps/libhashbrown-7062db69afd4722a.rlib target/release/deps/libtokio_util-f9a5800eb371f288.rlib target/release/deps/libfutures_sink-0793211ead5d4e6c.rlib target/release/deps/libtower_service-3a732bd16453ae7e.rlib target/release/deps/libtracing-021f8cc214139874.rlib target/release/deps/libtracing_core-c22b65bb5ec1efe9.rlib target/release/deps/libonce_cell-5e26bf523331b8e0.rlib target/release/deps/libfutures_channel-eb95f57d6814292d.rlib target/release/deps/libtokio-ed1061b4d4ac95f7.rlib target/release/deps/libnum_cpus-9eef86d3d5a42d34.rlib target/release/deps/libsocket2-d513d3c3ff81e5d3.rlib target/release/deps/libmio-b27fe499c1b81994.rlib target/release/deps/libsync_wrapper-33f1b3028f0801e2.rlib target/release/deps/libhttp_body-ceda74c453f7fb23.rlib target/release/deps/liblog-f39f6a76a0086a19.rlib target/release/deps/libfutures_util-9eee727b5281dd9b.rlib target/release/deps/libmemchr-128e6ce61c0ff28d.rlib target/release/deps/libfutures_io-08a182ea761140cc.rlib target/release/deps/libslab-0f1db8da5b920238.rlib target/release/deps/libpin_project_lite-1c23ed485efa1b06.rlib target/release/deps/libfutures_task-347d0c9381f7df63.rlib target/release/deps/libpin_utils-6a0d540de9e78030.rlib target/release/deps/libfutures_core-bb8b947a37521c5d.rlib target/release/deps/liburl-34d97ad5cb32b13d.rlib target/release/deps/libidna-95c7d6c417490fb9.rlib target/release/deps/libunicode_normalization-e823af57ae7ac103.rlib target/release/deps/libtinyvec-4197147df1778369.rlib target/release/deps/libtinyvec_macros-3018ee127284fcc5.rlib target/release/deps/libunicode_bidi-f6d5e0c2bba4f214.rlib target/release/deps/libform_urlencoded-5f9d984c143f197b.rlib target/release/deps/libpercent_encoding-946d30e440f29767.rlib target/release/deps/libhttp-62da6d27a134a4f7.rlib target/release/deps/libitoa-528a566125096185.rlib target/release/deps/libbytes-9966e59c6c110266.rlib target/release/deps/libfnv-82d0a40bbfed6e3d.rlib ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-0cd255ee414ee1b7.rlib ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-d94d981cfad2e302.rlib ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-bc5c85135ebc2d28.rlib ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-a783581261810918.rlib target/release/deps/libwalkdir-647cf2784a95b552.rlib target/release/deps/libsame_file-8a8cd61a6dfc5da4.rlib target/release/deps/libtar-05eaddab41c1519f.rlib target/release/deps/libxattr-3d63de4a63cd9eb5.rlib target/release/deps/librustix-78af8e3220ae7e77.rlib target/release/deps/libbitflags-4966c3690f2fe07a.rlib target/release/deps/liblinux_raw_sys-4606830f7af88dcd.rlib target/release/deps/libfiletime-aa12363e0730c517.rlib target/release/deps/liblibc-7e78217b691b030a.rlib target/release/deps/libflate2-729f997fb3ac51e3.rlib target/release/deps/libminiz_oxide-82c0cc6e343495b7.rlib target/release/deps/libadler-2c60a423fd987411.rlib target/release/deps/libcrc32fast-b7499fabf7baf5a4.rlib target/release/deps/libcfg_if-5f3dc791e81498f8.rlib target/release/deps/libanyhow-a3145dca07fb94b0.rlib target/release/deps/librayon-3e4ddcda55c922a3.rlib target/release/deps/librayon_core-b8488ed40d563cd8.rlib target/release/deps/libcrossbeam_deque-297ca0b1b68bf823.rlib target/release/deps/libcrossbeam_epoch-9ba9cfc2f4c9a373.rlib target/release/deps/libcrossbeam_utils-7dd2354cc82d25db.rlib target/release/deps/libeither-65a513fe0680a058.rlib target/release/deps/libsyn-89289939c25e83b8.rlib target/release/deps/libref_cast-35de96323af71460.rlib target/release/deps/libquote-6a37428a9e58049a.rlib target/release/deps/libproc_macro2-5a8ce56bdd6d2d2b.rlib target/release/deps/libunicode_ident-2651529e20c4ca92.rlib -L ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib -Wl,-Bdynamic -lrustc_driver-aa61d155f58600fb -L ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib -lstd-41777efa78699460 -Wl,-Bstatic ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b7903030bc1640bf.rlib -Wl,-Bdynamic -lssl -lcrypto -lLLVM-18-rust-1.78.0-nightly -ldl -lgcc_s -lutil -lrt -lpthread -lm -ldl -lc -Wl,--eh-frame-hdr -Wl,-z,noexecstack -L ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib -o target/release/deps/test_precedence-6bd9c16ceacbfa39 -Wl,--gc-sections -pie -Wl,-z,relro,-z,now -Wl,-O1 -Wl,--strip-debug -nodefaultlibs
  = note: /usr/bin/ld: cannot find -lLLVM-18-rust-1.78.0-nightly: No such file or directory
          collect2: error: ld returned 1 exit status