Install rustc_ast crate for the clippy CI job
    error[E0463]: can't find crate for `rustc_ast`
     --> tests/test_round_trip.rs:6:1
      |
    6 | extern crate rustc_ast;
      | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
      |
      = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`