Add regression test for issue 2081
    thread 'test_interpolated_lifetime_at_statement_start' (401040) panicked at tests/test_stmt.rs:363:5:
    expected `:`