Bump codegen build to newer rustfmt commit
The previously used rustfmt commit only builds with an early version of
1.51-dev, and that one is missing addr_of.

    error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
       --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.40/src/error.rs:606:14
        |
    606 |         ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
        |              ^^^^^^^ could not find `addr_of` in `ptr`

    error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
       --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.40/src/error.rs:647:22
        |
    647 |                 ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
        |                      ^^^^^^^ could not find `addr_of` in `ptr`