Raise required compiler for syn-codegen crate to 1.85
Required by indexmap 2.14.0.

    error: failed to download `indexmap v2.14.0`

    Caused by:
      unable to get packages from source

    Caused by:
      failed to parse manifest at `$CARGO_HOME/registry/src/index.crates.io-6f17d22bba15001f/indexmap-2.14.0/Cargo.toml`

    Caused by:
      feature `edition2024` is required

      The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.82.0 (8f40fc59f 2024-08-21)).
      Consider trying a newer version of Cargo (this may require the nightly release).
      See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.